# Generated by Django 2.0.3 on 2018-03-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('an_type', models.CharField(blank=True, max_length=50, null=True)),
                ('an_for', models.CharField(blank=True, max_length=50, null=True)),
                ('an_subject', models.CharField(blank=True, max_length=150, null=True)),
                ('an_description', models.CharField(blank=True, max_length=1250, null=True)),
            ],
        ),
    ]
