# Generated by Django 2.0.3 on 2018-03-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='an_description',
            field=models.TextField(blank=True, max_length=1250, null=True),
        ),
    ]
