# Generated by Django 2.0.3 on 2018-03-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20180328_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='an_for',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('Students', 'Students'), ('Doctors', 'Doctors')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='an_type',
            field=models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Administrative', 'Administrative')], max_length=50, null=True),
        ),
    ]
