# Generated by Django 2.0.3 on 2018-03-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_auto_20180325_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='level',
            field=models.CharField(blank=True, choices=[('Level 1', 'Level 1'), ('Level 1 continue', 'Level 1 continue'), ('Level 2', 'Level 2'), ('Level 2 continue', 'Level 2 continue'), ('Level 3', 'Level 3'), ('Level 3 continue', 'Level 3 continue'), ('Level 4', 'Level 4'), ('Level 4 continue', 'Level 4 continue')], max_length=50, null=True),
        ),
    ]
