# Generated by Django 2.0.3 on 2018-03-25 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_student_profile_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
