# Generated by Django 2.0.3 on 2018-03-26 02:04

import admin_dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('admin_dashboard', '0004_auto_20180325_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('highest_degree', models.CharField(blank=True, max_length=50, null=True)),
                ('university_high', models.CharField(blank=True, choices=[('Helwan', 'Helwan'), ('Cairo', 'Cairo'), ('Ain Shams', 'Ain Shams'), ('Mansora', 'Mansora'), ('Alex', 'Alex'), ('AUC', 'AUC')], max_length=50, null=True)),
                ('year_passed_high', models.DateField(blank=True, null=True)),
                ('gpa_high', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('other_degree', models.CharField(blank=True, max_length=50, null=True)),
                ('university_other', models.CharField(blank=True, choices=[('Helwan', 'Helwan'), ('Cairo', 'Cairo'), ('Ain Shams', 'Ain Shams'), ('Mansora', 'Mansora'), ('Alex', 'Alex'), ('AUC', 'AUC')], max_length=50, null=True)),
                ('year_passed_other', models.DateField(blank=True, null=True)),
                ('gpa_other', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=50, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(blank=True, choices=[('muslim', 'muslim'), ('christian', 'christian')], max_length=50, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=admin_dashboard.models.upload_img_doc)),
            ],
        ),
    ]
