# Generated by Django 2.0.3 on 2018-03-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_academicinfo_doctor_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='gpa_high',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='gpa_other',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='highest_degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='other_degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='university_high',
            field=models.CharField(blank=True, choices=[('Helwan', 'Helwan'), ('Cairo', 'Cairo'), ('Ain Shams', 'Ain Shams'), ('Mansora', 'Mansora'), ('Alex', 'Alex'), ('AUC', 'AUC')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='university_other',
            field=models.CharField(blank=True, choices=[('Helwan', 'Helwan'), ('Cairo', 'Cairo'), ('Ain Shams', 'Ain Shams'), ('Mansora', 'Mansora'), ('Alex', 'Alex'), ('AUC', 'AUC')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='year_passed_high',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='year_passed_other',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AcademicInfo',
        ),
    ]
