# Generated by Django 2.0.3 on 2018-03-31 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('code', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=1200, null=True)),
                ('doctor', models.ManyToManyField(blank=True, null=True, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(blank=True, null=True, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
