# Generated by Django 2.0.3 on 2018-03-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180331_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, max_length=1200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('courses', models.ManyToManyField(blank=True, to='courses.Course')),
            ],
        ),
    ]
