# Generated by Django 2.0.3 on 2018-04-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit_hours',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
