# Generated by Django 2.0.3 on 2018-04-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_credit_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3')], max_length=12, null=True),
        ),
    ]
