# Generated by Django 2.0.3 on 2018-04-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180402_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
