# Generated by Django 2.0.3 on 2018-03-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0002_auto_20180327_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=models.CharField(blank=True, max_length=1250, null=True),
        ),
    ]
