# Generated by Django 2.0.3 on 2018-03-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0003_auto_20180327_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_message', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=models.TextField(blank=True, max_length=1250, null=True),
        ),
    ]
