# Generated by Django 2.0.3 on 2018-03-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_system', '0004_auto_20180327_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagenotification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
